services:
  db:
    image: mysql:8.0
    container_name: nestjs-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: