import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "./providers";
import FloatingChatButton from "@/app/components/chat/FloatingChatButton";
import FloatingChatBotButton from "@/app/components/chat/FloatingChatBotButton";
import { ChatProvider } from "@/contexts/ChatContext";
import { SocketProvider } from "@/contexts/SocketContext";
import { UserProvider } from "@/contexts/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider dynamic>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Providers>
            <SocketProvider>
              <ChatProvider>
                <UserProvider>{children}</UserProvider>
                <FloatingChatBotButton />
                <FloatingChatButton />
              </ChatProvider>
            </SocketProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
